
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/Users/owen_guo/pushup/build/assets/frame2")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1680x1050")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 1050,
    width = 1680,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    960.0,
    525.0,
    image=image_image_1
)

canvas.create_text(
    795.0,
    89.0,
    anchor="nw",
    text="Statistics",
    fill="#FFFFFF",
    font=("RalewayRoman Bold", 100 * -1)
)

canvas.create_text(
    439.0,
    208.0,
    anchor="nw",
    text="Workout Log",
    fill="#FFFFFF",
    font=("RalewayRoman Bold", 70 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    723.0,
    378.0,
    image=entry_image_1
)
entry_1 = Text(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=439.0,
    y=341.0,
    width=568.0,
    height=72.0
)

canvas.create_text(
    32.0,
    40.0,
    anchor="nw",
    text="Pushup \nProgressor",
    fill="#FFFFFF",
    font=("RalewayRoman Bold", 55 * -1)
)

canvas.create_rectangle(
    -4.99981689453125,
    193.978515625,
    349.0,
    205.021484375,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    0.0,
    0.0,
    349.0,
    1050.0,
    fill="#EE7C7C",
    outline="")

canvas.create_rectangle(
    0.0,
    493.0,
    349.0,
    576.0,
    fill="#C74747",
    outline="")

canvas.create_rectangle(
    0.0,
    402.5,
    349.0,
    493.28125,
    fill="#C74747",
    outline="")

canvas.create_text(
    51.0,
    512.96875,
    anchor="nw",
    text="Progressions",
    fill="#FFFFFF",
    font=("RalewayRoman Bold", 40 * -1)
)

canvas.create_text(
    117.0,
    240.625,
    anchor="nw",
    text="Home",
    fill="#FFFFFF",
    font=("RalewayRoman Bold", 40 * -1)
)

canvas.create_text(
    92.0,
    331.40625,
    anchor="nw",
    text="Workout",
    fill="#FFFFFF",
    font=("RalewayRoman Bold", 40 * -1)
)

canvas.create_text(
    86.0,
    422.1875,
    anchor="nw",
    text="Statistics",
    fill="#FFFFFF",
    font=("RalewayRoman Bold", 40 * -1)
)

canvas.create_rectangle(
    1.0,
    320.0,
    350.0,
    403.0,
    fill="#C74747",
    outline="")

canvas.create_rectangle(
    0.0,
    232.0,
    349.0,
    315.0,
    fill="#C74747",
    outline="")

canvas.create_rectangle(
    434.0,
    298.0,
    872.0,
    308.0,
    fill="#FFFFFF",
    outline="")

canvas.create_text(
    1505.7750244140625,
    791.70703125,
    anchor="nw",
    text="Date",
    fill="#FFFFFF",
    font=("RalewayRoman Bold", 40 * -1)
)

canvas.create_text(
    1015.0,
    303.0,
    anchor="nw",
    text="Reps",
    fill="#FFFFFF",
    font=("RalewayRoman Bold", 40 * -1)
)

canvas.create_rectangle(
    1063.8910675048828,
    690.326171875,
    1131.153564453125,
    818.92041015625,
    fill="#EE7D7D",
    outline="")

canvas.create_rectangle(
    1364.7393188476562,
    404.5859375,
    1448.221435546875,
    532.04638671875,
    fill="#EE7D7D",
    outline="")

canvas.create_rectangle(
    1132.4321594238281,
    650.64013671875,
    1268.2357177734375,
    687.38916015625,
    fill="#EE7D7D",
    outline="")

canvas.create_rectangle(
    1266.3749694824219,
    523.64453125,
    1369.7392578125,
    655.64013671875,
    fill="#EE7D7D",
    outline="")

canvas.create_rectangle(
    1048.949951171875,
    350.82861328125,
    1058.949951171875,
    829.12548828125,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    1048.949951171875,
    819.12548828125,
    1491.1249389648438,
    829.12548828125,
    fill="#FFFFFF",
    outline="")

canvas.create_text(
    32.0,
    40.0,
    anchor="nw",
    text="Pushup \nProgressor",
    fill="#FFFFFF",
    font=("RalewayRoman Bold", 55 * -1)
)

canvas.create_rectangle(
    -4.99981689453125,
    193.978515625,
    349.0,
    205.021484375,
    fill="#FFFFFF",
    outline="")
window.resizable(False, False)
window.mainloop()
