
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/Users/owen_guo/pushup/build/assets/frame3")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1680x1050")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 1050,
    width = 1680,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    960.0,
    525.0,
    image=image_image_1
)

canvas.create_text(
    871.0,
    72.0,
    anchor="nw",
    text="Workout",
    fill="#FFFFFF",
    font=("RalewayRoman Bold", 70 * -1)
)

canvas.create_rectangle(
    1060.0,
    683.0,
    1235.0,
    742.0,
    fill="#EE7D7D",
    outline="")

canvas.create_text(
    731.0,
    683.0,
    anchor="nw",
    text="Reps Done:\n",
    fill="#FFFFFF",
    font=("RalewayRoman Bold", 55 * -1)
)

canvas.create_text(
    731.0,
    774.0,
    anchor="nw",
    text="Sets Done:",
    fill="#FFFFFF",
    font=("RalewayRoman Bold", 55 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    1151.0,
    715.0,
    image=entry_image_1
)
entry_1 = Text(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=1092.0,
    y=684.0,
    width=118.0,
    height=60.0
)

canvas.create_rectangle(
    1060.0,
    774.0,
    1235.0,
    833.0,
    fill="#EE7D7D",
    outline="")

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    1151.0,
    804.0,
    image=entry_image_2
)
entry_2 = Text(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=1107.0,
    y=773.0,
    width=88.0,
    height=60.0
)

canvas.create_rectangle(
    0.0,
    0.0,
    349.0,
    1050.0,
    fill="#EE7C7C",
    outline="")

canvas.create_rectangle(
    0.0,
    311.71875,
    349.0,
    402.5,
    fill="#C74747",
    outline="")

canvas.create_text(
    51.0,
    512.96875,
    anchor="nw",
    text="Progressions",
    fill="#FFFFFF",
    font=("RalewayRoman Bold", 40 * -1)
)

canvas.create_text(
    117.0,
    240.625,
    anchor="nw",
    text="Home",
    fill="#FFFFFF",
    font=("RalewayRoman Bold", 40 * -1)
)

canvas.create_text(
    92.0,
    331.40625,
    anchor="nw",
    text="Workout",
    fill="#FFFFFF",
    font=("RalewayRoman Bold", 40 * -1)
)

canvas.create_text(
    86.0,
    422.1875,
    anchor="nw",
    text="Statistics",
    fill="#FFFFFF",
    font=("RalewayRoman Bold", 40 * -1)
)

canvas.create_rectangle(
    1.0,
    229.0,
    350.0,
    312.0,
    fill="#C74747",
    outline="")

canvas.create_rectangle(
    0.0,
    403.0,
    349.0,
    486.0,
    fill="#C74747",
    outline="")

canvas.create_rectangle(
    0.0,
    487.0,
    349.0,
    570.0,
    fill="#C74747",
    outline="")

canvas.create_rectangle(
    557.7156372070312,
    186.48583984375,
    1464.4219360351562,
    636.228759765625,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    546.0,
    168.0,
    556.9089050292969,
    637.000244140625,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    1453.401123046875,
    168.0,
    1464.4208374023438,
    637.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    546.8578491210938,
    625.625244140625,
    1473.0,
    635.625244140625,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    547.8775634765625,
    168.0,
    1464.4208984375,
    178.0,
    fill="#FFFFFF",
    outline="")

canvas.create_text(
    32.0,
    40.0,
    anchor="nw",
    text="Pushup \nProgressor",
    fill="#FFFFFF",
    font=("RalewayRoman Bold", 55 * -1)
)

canvas.create_rectangle(
    -4.99981689453125,
    193.978515625,
    349.0,
    205.021484375,
    fill="#FFFFFF",
    outline="")
window.resizable(False, False)
window.mainloop()
