
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/Users/owen_guo/pushup/build/assets/frame4")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1680x1050")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 1050,
    width = 1680,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    960.0,
    525.0,
    image=image_image_1
)

canvas.create_rectangle(
    801.0,
    762.0,
    1229.0,
    851.0,
    fill="#C74747",
    outline="")

canvas.create_text(
    882.0,
    783.0,
    anchor="nw",
    text="Start Workout",
    fill="#FFFFFF",
    font=("RalewayRoman Bold", 40 * -1)
)

canvas.create_text(
    514.0,
    82.0,
    anchor="nw",
    text="Plan Workout Details",
    fill="#FFFFFF",
    font=("RalewayRoman Bold", 100 * -1)
)

canvas.create_rectangle(
    1107.0,
    369.0,
    1282.0,
    428.0,
    fill="#938383",
    outline="")

canvas.create_text(
    731.0,
    370.0,
    anchor="nw",
    text="Target Sets:\n",
    fill="#FFFFFF",
    font=("RalewayRoman Bold", 55 * -1)
)

canvas.create_text(
    731.0,
    461.0,
    anchor="nw",
    text="Reps / Set:",
    fill="#FFFFFF",
    font=("RalewayRoman Bold", 55 * -1)
)

canvas.create_text(
    731.0,
    552.0,
    anchor="nw",
    text="Time Limit:",
    fill="#FFFFFF",
    font=("RalewayRoman Bold", 55 * -1)
)

canvas.create_text(
    731.0,
    643.0,
    anchor="nw",
    text="Rest Time: ",
    fill="#FFFFFF",
    font=("RalewayRoman Bold", 55 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    1194.5,
    399.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=1181.0,
    y=368.0,
    width=27.0,
    height=60.0
)

canvas.create_rectangle(
    1107.0,
    551.0,
    1282.0,
    610.0,
    fill="#938383",
    outline="")

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    1193.0,
    490.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=1169.0,
    y=459.0,
    width=48.0,
    height=60.0
)

canvas.create_rectangle(
    1107.0,
    642.0,
    1282.0,
    701.0,
    fill="#938383",
    outline="")

canvas.create_rectangle(
    1107.0,
    460.0,
    1282.0,
    519.0,
    fill="#938383",
    outline="")

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    1193.0,
    490.0,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=1169.0,
    y=459.0,
    width=48.0,
    height=60.0
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    1193.0,
    672.0,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=1169.0,
    y=641.0,
    width=48.0,
    height=60.0
)

entry_image_5 = PhotoImage(
    file=relative_to_assets("entry_5.png"))
entry_bg_5 = canvas.create_image(
    1192.5,
    583.0,
    image=entry_image_5
)
entry_5 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_5.place(
    x=1165.0,
    y=552.0,
    width=55.0,
    height=60.0
)

canvas.create_rectangle(
    481.0,
    228.0,
    796.0,
    303.0,
    fill="#938383",
    outline="")

canvas.create_rectangle(
    857.0,
    228.0,
    1172.0,
    303.0,
    fill="#EE7D7D",
    outline="")

canvas.create_text(
    589.0,
    242.0,
    anchor="nw",
    text="Knee",
    fill="#FFFFFF",
    font=("RalewayRoman Bold", 40 * -1)
)

canvas.create_text(
    943.0,
    242.0,
    anchor="nw",
    text="Normal",
    fill="#FFFFFF",
    font=("RalewayRoman Bold", 40 * -1)
)

canvas.create_rectangle(
    1233.0,
    228.0,
    1548.0,
    303.0,
    fill="#938383",
    outline="")

canvas.create_text(
    1304.0,
    242.0,
    anchor="nw",
    text="Clapping",
    fill="#FFFFFF",
    font=("RalewayRoman Bold", 40 * -1)
)

canvas.create_rectangle(
    0.0,
    0.0,
    349.0,
    1050.0,
    fill="#EE7C7C",
    outline="")

canvas.create_rectangle(
    0.0,
    204.0,
    349.0,
    287.0,
    fill="#C74747",
    outline="")

canvas.create_rectangle(
    0.0,
    368.0,
    349.0,
    451.0,
    fill="#C74747",
    outline="")

canvas.create_rectangle(
    0.0,
    451.0,
    349.0,
    534.0,
    fill="#C74747",
    outline="")

canvas.create_rectangle(
    0.0,
    285.0,
    349.0,
    368.0,
    fill="#C74747",
    outline="")

canvas.create_text(
    51.0,
    469.0,
    anchor="nw",
    text="Progressions",
    fill="#FFFFFF",
    font=("RalewayRoman Bold", 40 * -1)
)

canvas.create_text(
    86.0,
    386.0,
    anchor="nw",
    text="Statistics",
    fill="#FFFFFF",
    font=("RalewayRoman Bold", 40 * -1)
)

canvas.create_text(
    92.0,
    303.0,
    anchor="nw",
    text="Workout",
    fill="#FFFFFF",
    font=("RalewayRoman Bold", 40 * -1)
)

canvas.create_text(
    117.0,
    220.0,
    anchor="nw",
    text="Home",
    fill="#FFFFFF",
    font=("RalewayRoman Bold", 40 * -1)
)

canvas.create_text(
    32.0,
    40.0,
    anchor="nw",
    text="Pushup \nProgressor",
    fill="#FFFFFF",
    font=("RalewayRoman Bold", 55 * -1)
)

canvas.create_rectangle(
    -4.99981689453125,
    193.978515625,
    349.0,
    205.021484375,
    fill="#FFFFFF",
    outline="")
window.resizable(False, False)
window.mainloop()
